const API_URL="/api/groundtrace",statusEl=document.querySelector("#status"),outputEl=document.querySelector("#output"),demoEl=document.querySelector("#demo"),demoStatus=document.querySelector("#demo-status");
function render(v){outputEl.textContent=JSON.stringify(v,null,2)}
async function groundTrace(payload,signal){const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),signal}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`GroundTrace returned ${r.status}`);render(b);return b}
const asToolResult=b=>({content:[{type:"text",text:JSON.stringify(b)}]});
async function runDemo(){demoEl.disabled=true;demoStatus.textContent="Remembering controlled precedent…";try{const tenant=`webmcp-demo-${Date.now()}`;await groundTrace({operation:"remember",tenant_id:tenant,incident_text:"API latency increased while database connection pool was saturated",action_text:"Inspect connection pool saturation and reduce burst concurrency",outcome_success:true,verified:true,occurred_at:new Date().toISOString(),provenance:{source:"controlled WebMCP demo incident"}});demoStatus.textContent="Recalling and evaluating precedent…";const result=await groundTrace({operation:"recall",tenant_id:tenant,incident_text:"API latency increased while database connection pool was saturated"});demoStatus.textContent=result.status==="RELY"?"PASS — precedent admitted with an inspectable warrant.":`Completed — ${result.status}.`; }catch(e){demoStatus.textContent=`FAIL — ${e.message}`;}finally{demoEl.disabled=false}}
demoEl?.addEventListener("click",runDemo);
async function registerTools(){if(!document.modelContext?.registerTool){statusEl.textContent="WebMCP is not available in this browser. Enable WebMCP or use ChatGPT's browser.";return}
await document.modelContext.registerTool({name:"groundtrace_recall",description:"Recall relevant prior operational incidents and return only recommendations admitted by GroundTrace's deterministic RELY/HOLD/REJECT warrant gate.",inputSchema:{type:"object",properties:{tenant_id:{type:"string"},incident_text:{type:"string"}},required:["tenant_id","incident_text"]},annotations:{readOnlyHint:false},execute:async({tenant_id,incident_text},{signal}={})=>asToolResult(await groundTrace({operation:"recall",tenant_id,incident_text},signal))});
await document.modelContext.registerTool({name:"groundtrace_remember",description:"Store a resolved operational incident with its action, outcome, verification state and provenance so it can become a future memory candidate.",inputSchema:{type:"object",properties:{tenant_id:{type:"string"},incident_text:{type:"string"},action_text:{type:"string"},outcome_success:{type:"boolean"},verified:{type:"boolean"},occurred_at:{type:"string"},provenance_source:{type:"string"}},required:["tenant_id","incident_text","action_text","outcome_success","verified","occurred_at","provenance_source"]},annotations:{readOnlyHint:false},execute:async(input,{signal}={})=>{const{provenance_source,...memory}=input;return asToolResult(await groundTrace({operation:"remember",...memory,provenance:{source:provenance_source}},signal))}});
await document.modelContext.registerTool({name:"groundtrace_explain",description:"Explain the warrant in the GroundTrace result currently visible on this page without inventing or overriding GroundTrace decisions.",inputSchema:{type:"object",properties:{}},annotations:{readOnlyHint:true},execute:async()=>{const text=outputEl.textContent.trim();if(!text||text==="No result yet.")return asToolResult({status:"NO_RESULT",message:"Run groundtrace_recall first."});const b=JSON.parse(text);return asToolResult({status:b.status,recommendation:b.recommendation,trace_id:b.trace_id,candidates:b.candidates,explanation:"Retrieved memory is a candidate, not authority. Only RELY candidates can supply a recommendation."})}});statusEl.textContent="WebMCP ready — 3 GroundTrace tools registered."}
registerTools().catch(e=>{statusEl.textContent=`WebMCP registration failed: ${e.message}`});